/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type BarcodeType = "group" | "lot" | "module" | "pallet" | "part" | "project" | "shipment" | "sub_module";

export type EdgeSide = "long_edge" | "short_edge";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MachineStatus = "available" | "busy" | "maintenance" | "offline";

export type MachineType = "cnc_drill" | "cnc_router" | "edge_bander" | "generic" | "manual_station" | "panel_saw";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OperationStatus = "done" | "failed" | "in_progress" | "pending" | "skipped";

export type PartStatus = "at_station" | "completed" | "done_at_station" | "in_progress" | "pending" | "rework" | "scrapped";

export type PartType = "external" | "manufactured" | "purchased_custom" | "purchased_stock";

export type ProjectType = "bathroom" | "kitchen" | "other" | "shop" | "wardrobe";

export type StationType = "assembly" | "banding" | "cnc" | "cutting" | "packaging";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type WoPriority = "high" | "low" | "normal" | "urgent";

export type WoStatus = "closed" | "open";

export interface Barcodes {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Generated<Json>;
  parent_id: string | null;
  /**
   * Polymorphic — type'a göre parts/modules/pallets/... tablosuna referans (FK yok)
   */
  source_ref: string;
  type: BarcodeType;
}

export interface EdgeBands {
  code: string;
  color: string | null;
  created_at: Generated<Timestamp>;
  description: string;
  geometry: string | null;
  id: Generated<string>;
  material: string | null;
  metadata: Generated<Json>;
  supplier: Generated<Json>;
  thickness_mm: Numeric | null;
}

export interface Machines {
  capabilities: Generated<string[]>;
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  machine_type: MachineType;
  metadata: Generated<Json>;
  model: string | null;
  name: string;
  station_id: string;
  status: Generated<MachineStatus>;
}

export interface Materials {
  category: string | null;
  code: string;
  created_at: Generated<Timestamp>;
  description: string;
  description_long: string | null;
  grain: Generated<boolean>;
  id: Generated<string>;
  metadata: Generated<Json>;
  supplier: Generated<Json>;
  thickness_mm: Numeric | null;
}

export interface Modules {
  article_number: string | null;
  /**
   * Proje içinde unique modül kodu
   */
  code: string;
  construction_principle: string | null;
  created_at: Generated<Timestamp>;
  dimensions: Generated<Json>;
  id: Generated<string>;
  images: Generated<Json>;
  is_assembled_at_factory: Generated<boolean>;
  metadata: Generated<Json>;
  /**
   * Esnek tip (base_cabinet, wall_cabinet, vb.) — enum dayatılmadı
   */
  module_type: string | null;
  name: string;
  project_id: string;
  weight_kg: Numeric | null;
}

export interface PartEdges {
  created_at: Generated<Timestamp>;
  edge_band_id: string;
  id: Generated<string>;
  machining_sides: Generated<number>;
  part_id: string;
  sequence: number;
  side: EdgeSide;
}

export interface PartOperations {
  actual_machine_id: string | null;
  alternative_machine_ids: Generated<string[]>;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  details: Generated<Json>;
  id: Generated<string>;
  part_id: string;
  phase: number;
  preferred_machine_id: string | null;
  required: Generated<boolean>;
  required_capabilities: Generated<string[]>;
  sequence: number;
  started_at: Timestamp | null;
  station: StationType;
  status: Generated<OperationStatus>;
}

export interface Parts {
  article_number: string | null;
  barcodes: Generated<Json>;
  code: string;
  created_at: Generated<Timestamp>;
  current_station_id: string | null;
  current_status: Generated<PartStatus>;
  description: string | null;
  dimensions: Generated<Json>;
  flags: Generated<Json>;
  grain_orientation_degrees: Numeric | null;
  id: Generated<string>;
  material_id: string | null;
  metadata: Generated<Json>;
  module_id: string;
  part_type: PartType;
  /**
   * Denormalize — UNIQUE(project_id, code) için; module.project_id ile senkron tutulmalı
   */
  project_id: string;
  quantity: Generated<number>;
  sub_module_id: string | null;
  supplier: Generated<Json>;
}

export interface Projects {
  /**
   * İnsan-okunur kod, ör. MUT-001 — UI ve barkodda görünür
   */
  code: string;
  created_at: Generated<Timestamp>;
  customer_address: string | null;
  customer_name: string | null;
  id: Generated<string>;
  /**
   * Kaynak sistem (IMOS) ek alanları — esnek şema
   */
  metadata: Generated<Json>;
  name: string;
  type: ProjectType;
}

export interface Stations {
  code: string;
  created_at: Generated<Timestamp>;
  display_order: Generated<number>;
  id: Generated<string>;
  name: string;
  station_type: StationType;
}

export interface SubModules {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Generated<Json>;
  module_id: string;
  name: string;
  sequence: Generated<number>;
}

export interface WorkOrders {
  code: string;
  created_at: Generated<Timestamp>;
  customer_name: string | null;
  id: Generated<string>;
  notes: string | null;
  planned_end_date: Timestamp | null;
  planned_start_date: Timestamp | null;
  priority: Generated<WoPriority>;
  /**
   * Birden fazla proje kapsayabilir (WO birleştirme); FK constraint array elemana uygulanmaz
   */
  project_ids: Generated<string[]>;
  status: Generated<WoStatus>;
}

export interface DB {
  barcodes: Barcodes;
  edge_bands: EdgeBands;
  machines: Machines;
  materials: Materials;
  modules: Modules;
  part_edges: PartEdges;
  part_operations: PartOperations;
  parts: Parts;
  projects: Projects;
  stations: Stations;
  sub_modules: SubModules;
  work_orders: WorkOrders;
}
